### ISSUE TITLE
[FR] Publish diagram in a more structural format

### ISSUE THREAD

**Issue by Zocker1999NET** [cole8888/SponsorBlock-Flowchart#12]
@cole8888 
I would like to reuse your flowchart and make it usable for example as interactive question form and for other ideas.
In theory I would just parse your draw.io diagram and would be happy but parsing the diagram seems very hard. So I have following questions:

1. I would opt to create (and maintain, if wished) a separate JSON (or maybe YAML) file describing the questions in your flowchart in a more systematic and easy-to-parse format. As it should be updated in parallel to the flowchart itself, I would like it to be published in this repository, too. If you share this opinion, I would then open a PR submitting the first port of the flowchart to this repo as well.
If you rather think such file would not fit in this repo, that would be fine for me as well. Then I would reside to open my own repo as kind of fork.

2. I'm currently just assuming that it would be okay for you that I reuse and publish your work as well. But because this repo is missing a license, I'm legally obliged to ask if it would be okay for you that I plan to copy and republish your work? I will mention you and your work appropriately and will release my adaption under a license you request (or CC-BY-SA if you do not care).

Thanks in advance and thank you for creating & maintaining this cool flowchart!

**Comment by cole8888** [comment]
Yes I would be willing to keep the JSON or YAML file up to date as the flowchart is updated, that won't be a problem! Feel free to make a PR.

CC-BY-SA sounds good to me, I will apply this license as soon as I check in with some people who handle the SponsorBlock wiki, since it needs to be under the same license they use since this is a derivative work of the wiki.

I have no problem with you reusing / republishing either so go ahead! :)

**Comment by mchangrh** [comment]
The wiki is under CC BY-SA 4.0, I can try to pull up a reference for it

https://wiki.sponsor.ajay.app/w/SponsorBlock:Copyrights

**Comment by mchangrh** [comment]
Since it's part of the process

I consent to licence my contributions to this project under CC BY-SA 4.0

**Comment by cole8888** [comment]
CC BY-SA 4.0 Applied, sorry I should have done that at the start :eyes:.
