### ISSUE TITLE
New Category for Epilepsy Warning?

### ISSUE THREAD

**Issue by Bullsquiddy** [cole8888/SponsorBlock-Flowchart#17]
Hello, I was thinking it might be useful to be able to create segments that indicate the presence of potentially dangerous flashing lights, or other photosensitivity risks. This might make it easier for people to not be caught off guard, and watch the rest of the video without fear of being put at risk.
Thank you.

**Comment by mchangrh** [comment]
wrong repository, see https://github.com/ajayyy/SponsorBlock/issues/403
