### ISSUE TITLE
Feature Request: Include identifiers on the flowchart

### ISSUE THREAD

**Issue by stdedos** [cole8888/SponsorBlock-Flowchart#9]
It might be easier to "communicate" a decision (and spot potential differences of opinions/flaws) if we could include the path to the decision taken.

If it is possible, it would be nice to add identifiers (e.g. numerical-ascending), so that e.g. an Endcards/Credits decision could be:
`6 > 14 > 15 > 26 > 37`

**Comment by cole8888** [comment]
Yeah I can look into something for this. Kinda busy lately with school so it will have to wait like a week or so.

**Comment by cole8888** [comment]
Sneak peek on what I got so far. Let me know your thoughts on how it looks or any changes you think should be made. I'm not sure if the numbers should increase going left to right or top to bottom. Flowchart logic is in the middle of being updated and hasn't been finalized yet so don't judge that! :P ![SB_Flowchart drawio](https://user-images.githubusercontent.com/32819560/156510937-1ecdf191-e57f-4371-a119-4bd1b72c9df9.png)

**Comment by stavros-mobal** [comment]
This is a work of art 🤩 

It's a "dummy" argument left-to-right/top-to-down; either way it works (unless someone has actual arguments regarding). FTR I had used top-down.

**Comment by stdedos** [comment]
This is a work of art 🤩 

It's a "dummy" argument left-to-right/top-to-down; either way it works (unless someone has actual arguments regarding). FTR I had used top-down.

**Comment by cole8888** [comment]
Added in v1.8.0
